name: Build PicoTorrent

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x86, x64]
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Synchronize submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Set up CMake
        uses: actions/setup-cmake@v3

      - name: Set up Visual Studio
        uses: actions/setup-msbuild@v1

      - name: Configure CMake
        run: cmake -B build -A ${{ matrix.arch == 'x86' && 'Win32' || 'x64' }}

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PicoTorrent-${{ matrix.arch }}
          path: build/Release/**
